# Generated by Django 4.0.3 on 2022-03-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
        ('cart', '0002_wishlist_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='wishlist.wishlist'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
